version: '2.5'


services:
  fastapi:
    build: fastapi/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi

  streamlit:
    build: streamlit/
    depends_on:
      fastapi:
        condition: service_started
    ports:
      - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit

  telegram:
    build: telegram/
    depends_on:
      fastapi:
        condition: service_started
    networks:
      - deploy_network
    container_name: telegram
    

networks:
  deploy_network:
    driver: bridge
