from aiogram.fsm.state import State, StatesGroup


class ProjectStates(StatesGroup):
    train_type_select = State()
    model_select = State()
    hyperparam_select = State()
    hyperparam_value = State()
    loss_select = State()
    device_select = State()
    optim_select = State()
    optim_param_select = State()
    optim_param_value = State()
    batch_size_input = State()
    test_size_input = State()
    epochs_num_input = State()
    time_limit_input = State()
    model_id_input = State()
    metric_select = State()
    load_train_file = State()
    load_predict_file = State()
    training = State()
    model_remove = State()
    model_load = State()
    predict = State()